### ISSUE TITLE
Low quality video

### ISSUE THREAD

**Issue by bolemebrige** [Fyusion/LLFF#17]
Hi,

I have to scale number of planes of neural network so I can run it on my graphics card so when I get the output video it has really bad quality. Can you explain me how to scale this software to work on graphics card with lower computation power while preserving the video quality?

**Comment by bmild** [comment]
How much memory does your GPU have? Here I mentioned how to force the code to run the network in smaller patches so that it will use less memory, for someone with 4GB of GPU memory:
https://github.com/Fyusion/LLFF/issues/11#issuecomment-516905659
That variable `valid` controls the size of the patches, so if you make it small enough you should be able to run with 32 or 64 planes. The processing time will increase proportional to the number of patches though.

**Comment by bolemebrige** [comment]
2 GB, I scaled valid variable to 108 to make it possible on 2 GB and iz outputs video but still in bad quality as seen on attached picture.
![ from crop17-20-02](https://user-images.githubusercontent.com/35038922/66330242-e2d33680-e927-11e9-839f-ed1f51523530.png)


Thank you!

**Comment by bolemebrige** [comment]
I made it, thank you :)
