### ISSUE TITLE
Unable to use light field datasets other than the testscene

### ISSUE THREAD

**Issue by CriusT** [Fyusion/LLFF#20]
Hi, I have finished the installation and rendered the testscene successfully. However, when I tried to use pictures from other datasets, I just failed. The dataset I use is the [MIT Synthetic Light Field Archive](http://web.media.mit.edu/~gordonw/SyntheticLightFields/index.php).
I checked the log and I found the first error occured here: 

```
Need to run COLMAP
Features extracted
Features matched
Sparse map created
Finished running COLMAP, see data/carscene/output_5x5m/colmap_output.txt for logs
Post-colmap
('Cameras', 5)
('Images #', 2)
Traceback (most recent call last):
  File "imgs2poses.py", line 11, in <module>
    gen_poses(args.scenedir)
  File "/host/data2/l00362246/boyutian/LLFF/llff/poses/pose_utils.py", line 273, in gen_poses
    save_poses(basedir, poses, pts3d, perm)
  File "/host/data2/l00362246/boyutian/LLFF/llff/poses/pose_utils.py", line 63, in save_poses
    cams[ind-1] = 1
IndexError: list assignment index out of range
```
The scene I use contains 25 pictures, but only 2 pictures(the initial pair) has been registered successfully after running COLMAP. I think this is the main reason for the failure. I was wondering why that happens. Also, I checked the colmap output. One of the differences is that the pictures I use do not contain GPS information. I attach the colmap_output here.
[car_colmap_output.txt](https://github.com/Fyusion/LLFF/files/3802480/car_colmap_output.txt)

**Comment by CriusT** [comment]
Also, I was also wondering is there a way to change the frame rate of the output video?

**Comment by bmild** [comment]
To change the framerate output from the CUDA renderer, change both instances of the number "30" to whatever fps you want [here](https://github.com/Fyusion/LLFF/blob/master/cuda_renderer/main.cu#L53) (this is the ffmpeg command that creates the video) and recompile.

Unfortunately we are currently dependent on the success of COLMAP to run our algorithm since it requires camera poses, see my comments [here](https://github.com/Fyusion/LLFF/issues/8#issuecomment-498514411).

In this case of the MIT light field data, I'm guessing the baseline might be too small for COLMAP to handle. However, the exact poses should be available in the README.txt file included with the images. But... I think these renderings might not be using a typical pinhole projection model because the principal point may not be centered -- I think they might be imaging a fixed rectangular "focal" window but from different points on a second "aperture" plane. If true, they do not act like images from a physical camera and would break the assumption in our code of a centered principal point...

**Comment by CriusT** [comment]
OK. Thanks a lot! I will use images from physical camera instead.

**Comment by ibtehajali67** [comment]
i am also facing that issue
